name: 'Twitch OpenAPI Generator'
description: 'Generates an OpenAPI Spec from the Twitch Helix API docs'
runs:
  using: 'composite'
  steps:
    - name: Copy Crawler
      run: cp -R ${{ github.action_path }}/src . && cp ${{ github.action_path }}/package.json .
      shell: bash
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install Dependencies
      run: npm install
      shell: bash
    - name: Get Docs Updates
      uses: ianwalter/puppeteer-container@v4.0.0
      with:
        args: node .
    - name: Cleanup
      run: rm -R src && rm package*.json && rm -R node_modules
      shell: bash