name: 'Twitch OpenAPI Generator'
description: 'Generates an OpenAPI Spec from the Twitch Helix API docs'
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      uses: ianwalter/puppeteer-container@v4.0.0
      with:
        args: pnpm i ${{ github.action_path }}
    - name: Get Docs Updates
      uses: ianwalter/puppeteer-container@v4.0.0
      with:
        args: node ${{ github.action_path }}/src/index.js