name: 'Twitch OpenAPI Generator'
description: 'Generates an OpenAPI Spec from the Twitch Helix API docs'
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      uses: tj-actions/puppeteer@v3.2
      with:
        args: npm install ${{ github.action_path }}
    - name: Get Docs Updates
      uses: tj-actions/puppeteer@v3.2
      with:
        args: node ${{ github.action_path }}/src/index.js